FROM python:3.10-slim

WORKDIR /app

COPY requirements-train.txt /app/requirements-train.txt
RUN pip install --no-cache-dir -r requirements-train.txt

COPY main-train.py /app/main-train.py

CMD ["python", "main-train.py"]
